---
# role: jomrr.podman
# file: .pre-commit-config.yaml

repos:
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v26.8.0
    hooks:
      - id: ansible-lint
        always_run: false
        entry: ansible-lint --force-color --offline --profile production .
        language: python
        pass_filenames: false
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
