[project]
name = "podman"
version = "1.0-beta.1"
description = "Install Podman and manage engine, storage, registry and rootless account configuration."
requires-python = ">=3.12"
authors = [
  { name = "Jonas Mauer" },
]
license = "MIT"
keywords = ["ansible", "role", "podman"]

[project.urls]
Repository = "https://github.com/jomrr/ansible-role-podman"

[tool.uv]
package = false

[dependency-groups]
ansible = [
  "ansible-core==2.20.*",
  "ansible-lint==26.*",
]

podman = [
  "molecule==26.*",
  "molecule-plugins[podman]==25.*",
]

[tool.commitizen]
name = "cz_conventional_commits"

[tool.semantic_release]
branch = "main"
commit_message = "build(release): version {version}"
major_on_zero = true
upload_to_pypi = false
upload_to_vcs_release = true
tag_format = "v{version}"
version_toml = [
    "pyproject.toml:project.version",
]
