---
# role: jomrr.podman
# file: tasks/main.yml

- name: Set os_family dependent variables
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  ansible.builtin.include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Include tasks for installing podman
  ansible.builtin.include_tasks: setup.yml

- name: Include tasks for /etc/containers configuration
  ansible.builtin.include_tasks: conf.yml
  when: podman_configure | bool

- name: Include tasks for sysctl configuration
  ansible.builtin.include_tasks: sysctl.yml

- name: Include tasks for subuid/subgid mappings and user config
  ansible.builtin.include_tasks: users.yml
