---
# role: podman
# file: tasks/main.yml

- name: PODMAN | Load platform packages
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"

- name: PODMAN | Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ __podman_packages }}"
    state: present

- name: PODMAN | Configure system containers
  ansible.builtin.import_tasks: conf.yml
  when: podman_configure

- name: PODMAN | Configure selected accounts
  ansible.builtin.include_tasks: users.yml
  loop: "{{ podman_users | dict2items }}"
  loop_control:
    loop_var: __podman_user
    label: "{{ __podman_user.key }}"
