---
# role: jomrr.podman
# file: molecule/default/molecule.yml

scenario:
  name: default
dependency:
  name: galaxy
  requirements-file: meta/requirements.yml
driver:
  name: podman
lint: set -e; ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        podman_users:
          root: '100000:65535'
          vagrant: '165536:65535'
verifier:
  name: ansible
platforms:
  - name: podman
    image: docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
