---
# role: ansible-role-podman
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: podman-default
    image: ${MOLECULE_DIST:-"jomrr/ubuntu-molecule:18.04"}
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        podman_enabled: True
        podman_configure: True
        podman_users:
          root: '100000:65535'
        podman_storage_driver: 'vfs'
        podman_storage_mountopt: ''
        podman_conf_cgroup_manager: 'cgroupfs'
        podman_conf_events_logger: 'file'
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: false
  lint:
    name: flake8
