---
# role: podman
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        podman_configure: true
        podman_conf_cgroup_manager: "cgroupfs"
        podman_storage_driver: "vfs"
        podman_storage_graphroot: "/var/lib/podman-molecule"
        podman_storage_rootless_path: "{{ ansible_facts.getent_passwd['podman_service'][4] }}/podman-molecule-storage"
        podman_storage_options:
          vfs:
            ignore_chown_errors: "false"
        podman_users:
          podman_service: "11000:4096"
        podman_search_registries: []
        podman_insecure_registries: []
        podman_blocked_registries:
          - "blocked.example.invalid"
        podman_registries:
          - prefix: "images.example.invalid/library"
            location: "docker.io/library"
            mirror:
              - location: "quay.io/libpod"
        podman_registry_aliases:
          podman-smoke: "images.example.invalid/library/busybox"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "check"
    - "idempotence"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-podman"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
  - name: "debian-latest-podman"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
  - name: "fedora-latest-podman"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
  - name: "opensuse-leap-latest-podman"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
  - name: "opensuse-tumbleweed-latest-podman"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
  - name: "ubuntu-latest-podman"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
